name: release

on: [push, pull_request, workflow_dispatch]
    
env: 
  DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
  APPLICATION_NAME: rife-ncnn-vulkan

jobs: 

  setup:
    runs-on: ubuntu-latest
    outputs:
      APPNAME: ${{ steps.get_appname.outputs.APPNAME }}
      VERSION: ${{ steps.get_version.outputs.VERSION }}
    steps:
    - name: get-appname
      id: get_appname
      run: echo ::set-output name=APPNAME::${APPLICATION_NAME}
    - name: get-version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}


  windows-arm:
    needs: [setup]
    runs-on: windows-11-arm
    env:
      PACKAGENAME: ${{ needs.setup.outputs.APPNAME }}-${{ needs.setup.outputs.VERSION }}-windows-11-arm
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Prepare Vulkan SDK
      uses: humbletim/setup-vulkan-sdk@v1.2.1
      with:
         vulkan-query-version: 1.4.304.1
         vulkan-components: Vulkan-Headers, Vulkan-Loader
         vulkan-use-cache: true
   
    - name: build
      run: |
        mkdir build; cd build
        cmake -A x64 ../src
        cmake --build . --config Release -j 2
    - name: package
      run: |
        mkdir ${{ env.PACKAGENAME }}
        Copy-Item -Verbose -Path "README.md" -Destination "${{ env.PACKAGENAME }}"
        Copy-Item -Verbose -Path "LICENSE" -Destination "${{ env.PACKAGENAME }}"
        Copy-Item -Verbose -Path "build\Release\${{ needs.setup.outputs.APPNAME }}.exe" -Destination "${{ env.PACKAGENAME }}"
        Copy-Item -Verbose -Path "C:\windows\system32\vcomp140.dll" -Destination "${{ env.PACKAGENAME }}"
        Copy-Item -Verbose -Recurse -Path "models\*" -Destination "${{ env.PACKAGENAME }}"
        7z a -r ${{ env.PACKAGENAME }}.zip ${{ env.PACKAGENAME }}
    - name: log release
      run: |
         dir
         cd build
         dir
         cd Release
         dir
         
    - name: log
      run: |
          cd D:\a\rife-ncnn-vulkan\rife-ncnn-vulkan\rife-ncnn-vulkan-refs\heads
          dir
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: windows-11-arm
        path: D:\a\rife-ncnn-vulkan\rife-ncnn-vulkan\rife-ncnn-vulkan-refs\heads\master-windows.zip
